-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS USER_ROLE(
    ID SERIAL PRIMARY KEY , 
    USER_ID INT NOT NULL , 
    ROLE_ID BIGINT UNSIGNED NOT NULL , 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , 

    CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE , 
    CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE
)
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS USER_ROLE ; 
-- +goose StatementEnd
