-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS PERMISSION(
    ID SERIAL PRIMARY KEY  , 
    NAME VARCHAR(50) NOT NULL UNIQUE, 
    DESCRIPTION TEXT , 
    RESOURCE VARCHAR(50) NOT NULL , 
    ACTION VARCHAR(50) NOT NULL , 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS PERMISSION ; 
-- +goose StatementEnd
