-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS ROLE_PERMISSION(
    ID SERIAL PRIMARY KEY , 
    ROLE_ID BIGINT UNSIGNED NOT NULL , 
    PERMISSION_ID BIGINT UNSIGNED NOT NULL , 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP , 

    CONSTRAINT FK_ROLE_PERMISSION_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID) ON DELETE CASCADE
) ; 
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ROLE_PERMISSION;
-- +goose StatementEnd
