-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS ROLE(
    ID SERIAL PRIMARY KEY , 
    NAME VARCHAR(50) NOT NULL UNIQUE, 
    DESCRIPTION TEXT , 
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP , 
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS ROLE;
-- +goose StatementEnd
